not_enough_scrap =[
    '<ERROR INVALID SCRAP INPUT>',
    'You don\'t have enough scrap to send me anywhere.',
    'MrDestructoid Error. Insufficient funds.',
    'Insuffcient scrap',
    'I cannot travel on hopes and dreams, you require more scrap.',
    '001101010000011111'
]

no_wiki_entry = [
    'I went to a strange land and didn\'t speak the language',
    'Well, I went somewhere, that\'s for sure.',
    '<ERROR NO VALID ENTRY FOUND>',
]

i_got_lost =[
    'I got lost MrDestructoid',
    '<ERROR DESTINATION NOT FOUND>',
    '404 destination not found',
    'GPS Data Corrupted',
    'Recalculating...recalculating...make a U-Turn ahead',
    'Location dissipating'
]

uwus = [
    'uWu',
    'oWo',
    'UWU :3',
    'UwU',
    ':3',
    'nyxiative\'s mouse pad',
    '(ᵘʷᵘ)',
    '(ᵘﻌᵘ)',
    '˯˽˯',
    '(◡ ω ◡)',
    '(◡ u ◡)',
    '(◡ w ◡)',
    '(◡ ሠ ◡)',
    '(˘ω˘)',
    '(⑅˘꒳˘)',
    '(˘ᵕ˘)',
    '(˘ሠ˘)',
    '(˘³˘)',
    '(˘ε˘)',
    '(´˘`)',
    '(´^`)',
    '(˘ ^ ˘)',
    '( ᴜ ω ᴜ )',
    '( ´ω` )۶',
    '(„ᵕᴗᵕ„)',
    '(*ฅ́˘ฅ̀*) ',
    '(ㅅ ˘ )',
    '(⑅˘˘)',
    '( ｡ᵘ ᵕ ᵘ ｡)'
]

six_nines =[
    'Heh, 69, nice.',
    'Nice.',
    'Heh, nice.',
    "C'est bon.",
    'noice.',
    'N I C E',
    'n i c e',
    'ecin o_o',
    'NAAICEE',
    '69? Nani?!'
]

generic_forgive_messages = [
    'I forgive you.',
    'Apology Accepted.',
    'It\'s fine, really. I\'m not mad. I don\'t hold grudges.',
    'Ok, but don\'t do it again.',
    'It\'s not your fault, it\'s mine.',
    'MrDestructoid <OUTPUT FORGIVENESS MESSAGE> MrDestructoid'
]
generic_harass_messages =[
    'BabyRage',
    'This means war.',
    #Thanks exegete46
    'owo am angy now.',
    '<Tilt mode initiated>'
]
generic_success_messages = [
    'Nailed it',
    'All set',
    'Done',
    'MrDestructoid <OUTPUT SUCCESS MESSAGE> MrDestructoid',
    'Yes daddy.',
    'This is a generic success response.',
    #Thanks Alcaeus
    'Response : 200 OK'
]

generic_fail_messages = [
    "I'm afraid I can't let you do that.",
    "No.",
    "Nope.",    
    "I don't wanna",
    "This is generic failure response",
    "I'm not gonna, and I'm telling on you.",
    "MrDesctructoid <OUTPUT FAILURE MESSAGE> MrDesctructoid",
    #Thanks Alcaeus
    "Negative Ghostrider",
    "404 Response not found",
    #Thanks Efleming969
    "This is not the droid you are looking for.",
    #Thanks Mecke_Dev
    "Error 401: Access denied."
]

admins = [
    'pronerd_jay',
    'frostops07',
    'sublimiter'
]

static_commands =[      
    '!addop',
    '!deputize',
    '!rmop',
    '!fire',
    '!about',
    '!commands',
    '!followage',
    '!uptime',
    '!insult',
    '!compliment',
    '!hotness',
    '!addcommand',
    '!raffle',
    '!draw'
]

suicide = [
    'kill myself',
    'kill yourself',
    'i want to die'
]

emotes = [
    'skyzmNuke',
    'skyzmSoar',
    'skyzmGhosty',
    'skyzmShred',
    'skyzmBits',
    'skyzmBurp',
    'skyzmBaby',
    'skyzmCorrect',
    'skyzmCrown'
]

harass_cues = [
    'nurdbutt',
    'nerdbutt',
    'nerdbot',
    'fuck you nurdbot',
    'fck u nurdbot',
    'nurd butt',
    'nurdburtis',
    'nurd butis',
    'nerdburtis',
    'nerd burtis',
    'nerfbutt',
    'nurtbutt',
    'i am republican',
    'nordbot',
    'nord bot',
    'nordVPN #Ad',
    'turdbot',
    'noobbot',
    'nurdbot fight me',
    'nurdbot fite me',
    'nurdbot u wot m8',
    'nurdbot sux',
    'nurdbot sucks',
    'nurfbutt',
    'you suck nurdbot',
    'nurdbot is trash'
]

forgive_cues = [
    'nurdbot i am sorry',
    'i am sorry nurdbot',
    "i'm sorry nurdbot",
    "nurdbot i'm sorry",
    'nurdbot im sorry',
    'im sorry nurdbot'
    'my bad nurdbot',
    'forgive me nurdbot',
    'sorry nurdbot',
    'nurdbot, im sorry',
    "nurdbot, i'm sorry"
]

love_definitions = [
    '<#',
    '<3',
    'Well you see, when a mommy and daddy love each other very much...or tequila is involved <ERROR ERROR>',
    'when skyzmLP calls us annoying.',
    'Sonny, rue love is the greatest thing in the world. Except for a nice M.L.T., a mutton, lettuce, and tomato sandwich, where the mutton is nice and lean, and the tomato is ripe. They’re so perky. I love that.',
    'Wuv...TRUE Wuv....is what bwings us twogeva....Today',
    'uWu',
    'Mawage. Mawage is wot bwings us togeder tooday. Mawage, that bwessed awangment, that dweam wifin a dweam… And wuv, tru wuv, will fowow you foweva… So tweasure your wuv.',
    'Love, giving them the last piece of cake even though you really want it...Father what is cake?',
    'My understanding of love, from the internet, involves Shrek SMOrc',
    "love is like a fart. If you have to force it, it's probably shit",
    'Love is a potato full of broken glass, it stinks at first but then you ring a doorbell'

]

nurdbot_definitions =[
    'A totally awesome psuedo AI.',
    'A bot that knows what love is allegedly.',
    'that weird dude you keep around just cause, but then he turns out to be your best friend the rest of your life',
    "A pseudo-sentient twitch chat anomoly born in skyzmLP's chat.",
    "A crab once taught me humor.",
    "Nurdbot is true.",
    "Wait, it's all Nurdbot? Always has been.",
    "Nurdbot is a cross dimensional AI that communicates via a proprietary quantum tunneling interface"

]

life_definitions = [
    '42',
    'Skyzm',
    'Shrek is both love and life',
    'Life is KappaPride',
    'Life is MadamCommander streams',
    'Life can be defined as a consciousness that drives a disgusting meat puppet',
    "It's worth it.",
    "Life is not a fairy tale. If you lose your shoe at midnight, you're drunk."
]

known_bots = [
        "pretzelrocks",
        "0vsyan0chka",
        "0x2f7c37",
        "0x4c554b49",
        "1111azazazel1111",
        "111phantom111",
        "1fps",
        "1k_dnar",
        "1o1aw01f",
        "228papiroska",
        "30vs1",
        "33cows33",
        "4chan",
        "4esta4",
        "6madhatter9",
        "777vadik777",
        "8drinkdrankdrunk8",
        "9kmmrbot",
        "a1bear",
        "aborigenich",
        "abrocome",
        "abuzerwispa",
        "acecasper",
        "ackrosgliceas",
        "addison17388",
        "adreou",
        "adsk1gam3r",
        "adskiflekser",
        "afrikanic",
        "agantor",
        "agentgabena0007",
        "agregation",
        "aksamitnyi",
        "alejords",
        "alfredjudokus100289",
        "allvoltage_au",
        "ammonium",
        "andre_r91",
        "angeloflight",
        "anotherttvviewer",
        "antares0",
        "apex_pro_community",
        "arborway",
        "artjomv2",
        "artyrus2",
        "aten",
        "atomspalte",
        "attilagadila",
        "awwcookies",
        "b0tau",
        "b10ckparty",
        "baaed",
        "babkasdrobovikom",
        "bagbread",
        "baldymixi",
        "balogir",
        "banmonitor",
        "barisbritvva",
        "bastaard",
        "beaverboybc",
        "beethovenian",
        "benbruc3",
        "bichcraft1998",
        "bilikirs",
        "binplate",
        "bisvin3",
        "bloodlustr",
        "bloodsuca",
        "bluejeans17",
        "boberche",
        "bockwurstblinkermitsenf",
        "bogddaann",
        "bolotnik3",
        "booonstick",
        "boothian",
        "bosscitys_finest",
        "bouaf",
        "boxxeer",
        "boyachek",
        "boyfriendtvoeimamki",
        "brandomsalas",
        "brickbybrick007",
        "bristlerich",
        "brokallii",
        "bryn3tt",
        "bundeli",
        "calcaria",
        "capitanbratan",
        "cepnoipes",
        "chargeman",
        "chooseneye",
        "chupokabri4",
        "cinfol",
        "citbds",
        "ck8t",
        "cloudrap12",
        "commanderroot",
        "commula",
        "communityshowcase",
        "coziest",
        "cptteempo",
        "crazycynical",
        "creatingcraziness",
        "creepermellow",
        "cristofer2001isback",
        "crunchipchip",
        "curtisvalentine",
        "cxatikot",
        "d0ntfckwthmexico",
        "d3athprofesor",
        "daaarling02",
        "dancing666devil",
        "dandancerr",
        "daniilka911",
        "dataoctopus",
        "dbc__",
        "dcppodrostok",
        "deep5",
        "denelewinski",
        "derik_lav",
        "devenleo",
        "devilboichik",
        "devils_dog_gaming",
        "disc0t3ka",
        "divarion",
        "djsketch04",
        "dodoxfortnite",
        "domett",
        "dorienabg",
        "dr0vosik",
        "droelf_zehn",
        "ducfever_gaming",
        "dunasbh",
        "dwine",
        "eadith",
        "eduaard",
        "einfachwir",
        "elasmosaur",
        "electricallongboard",
        "emi1yxoxo",
        "eminencek",
        "enrixeb",
        "evangelizes",
        "evelong",
        "explodedsoda",
        "ezbrorelax",
        "ezhikkot",
        "ezt1ger",
        "f0ocys",
        "fabrikamolochnici",
        "fanboiblizzarda",
        "fannt1kk",
        "fantassyman",
        "fathead_69",
        "faze_tryhard124",
        "fbrchika",
        "fearms1",
        "feet",
        "fingerection",
        "fjdkslazxc12",
        "forsale18",
        "freast",
        "freddyybot",
        "g1idai1",
        "gabrigode",
        "galgoya",
        "galisibbi",
        "gamingcenter111",
        "ganja",
        "garvsehgal98",
        "gash360332",
        "gazza1205",
        "gena300000",
        "ghfntm27271",
        "gingerne",
        "gkgus0823",
        "grifordia",
        "grizzilk",
        "guilyan_lp",
        "gzipped",
        "hallowokirschsaft",
        "herr_huebenbecker",
        "heyitsbluxd",
        "horek2",
        "hosthighway",
        "hostmeraffle",
        "hosttrader",
        "huddler",
        "humptata0815",
        "icetoast_on_twitch",
        "igorr_79",
        "igromaniak_pro",
        "im_balance_",
        "infiltration10",
        "inventkin",
        "itsvodoo",
        "itz_sam09",
        "ivangrowler",
        "jamofdestiny",
        "jener_uhrmacher",
        "jimmyjongos",
        "jochenrindt",
        "jounybouy36",
        "k03256",
        "kannami_yuichi",
        "kartezzzhnik",
        "koshkakoritsa",
        "kostyan4ick1",
        "kousa",
        "krodogs",
        "lcduser",
        "lemonjuices12",
        "leprosies",
        "lillypain",
        "lipster09",
        "liquigels",
        "llabisa",
        "llorx_falso",
        "loris11",
        "luffybazooka_14",
        "luki4fun_bot_master",
        "lukix29",
        "lurk24",
        "lurk_rts",
        "lurkernetwork",
        "lurxx",
        "m0876",
        "madeiras",
        "magi_system",
        "makruu",
        "manipulable",
        "materfamilias",
        "mathgoat",
        "maxwell_bo",
        "miafeelgood",
        "miki_57",
        "mikuia",
        "mindoflurk",
        "mojave_narwhal",
        "n0tahacker_",
        "n3td3v",
        "needhymn",
        "nefs",
        "nodurex4you",
        "nt_x",
        "nympholept",
        "obeycrow",
        "olleduner",
        "oncefamousgaming",
        "ooo_star_ooo",
        "osccraig",
        "p0lizei_",
        "paytv50",
        "phefo",
        "pimpstyle9008",
        "pingutio",
        "planetendreher",
        "pocrevocrednu",
        "poposohappy",
        "prankcher",
        "psrts",
        "q900481",
        "rans4cker",
        "red__swallow",
        "reifendreher",
        "rimastino",
        "rizlim16",
        "ronyrollin",
        "rubberslayer",
        "rutonybot",
        "ryothscus",
        "s1faka",
        "sampker7",
        "sana_drinks_isklar",
        "satistarr",
        "schmantfredo",
        "scomttv",
        "scottiqu",
        "scratchdee",
        "secretlyyours",
        "seelenkerker",
        "senadani",
        "seniorpomidor",
        "sethurlp",
        "shikimori19",
        "shinylion0078",
        "sibbigali",
        "skinnyseahorse",
        "skumshop",
        "skystridertag",
        "sling011r",
        "smallstreamerssupporter",
        "snorlax717",
        "srizbi",
        "ssakdook",
        "sss8787",
        "storecina",
        "stream_lurkers_united",
        "streamholics",
        "stripfang",
        "swampnugg",
        "taichi22141020",
        "tech_support_alan",
        "the_aydin",
        "the_hosting_asylum",
        "thedevilisob",
        "thedigitallink",
        "thewritinger",
        "tjsbot",
        "tookills",
        "toxic_cat",
        "trankhanh12",
        "tresinno",
        "trifelife",
        "troyfullbuster",
        "trucha0903",
        "tteyyd",
        "ttvlogger",
        "twitchcancermonitor",
        "twitchdatamining",
        "twitchprimereminder",
        "uberkosh5",
        "uehebot",
        "undefined_ninja",
        "universe",
        "unsaying",
        "v_and_k",
        "vanilaunity",
        "vasjapirat",
        "virgoproz",
        "vitallikn",
        "volvoxtriton",
        "vrodah",
        "warpmemories",
        "wehypebot",
        "winsock",
        "woos_bot",
        "xatang",
        "xgrelx",
        "yardi108",
        "yoremeofga",
        "youssefs12",
        "yt_lunolp_yt",
        "zalonecrowz",
        "zeeqfx",
        "zl10_719",
        "zombie_ee",
        "zygzak_mcqueen_"
    ]

